export default {
  DASHBOARD_PROJECTS_GET_ALL_SUBMITTED: 'DASHBOARD:PROJECTS:GET_ALL:SUBMITTED',
  DASHBOARD_PROJECTS_GET_ALL_APPEND_ONE: 'DASHBOARD:PROJECTS:GET_ALL:APPEND_ONE',
  DASHBOARD_PROJECTS_GET_ALL_SUCCEEDED: 'DASHBOARD:PROJECTS:GET_ALL:SUCCEEDED',
  DASHBOARD_PROJECTS_GET_ALL_FAILED: 'DASHBOARD:PROJECTS:GET_ALL:FAILED',
};
