export default {
  AUTH_LOGIN_SUBMITTED: 'AUTH:LOGIN:SUBMITTED',
  AUTH_LOGIN_SUCCEEDED: 'AUTH:LOGIN:SUCCEEDED',
  AUTH_LOGIN_FAILED: 'AUTH:LOGIN:FAILED',
  AUTH_LOGOUT_SUBMITTED: 'AUTH:LOGOUT:SUBMITTED',
  AUTH_LOGOUT_SUCCEEDED: 'AUTH:LOGOUT:SUCCEEDED',
};
